name: 'update'

on:
  schedule:
    - cron: 0 0 15 * *
  workflow_dispatch:
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@main
        with:
          ref: main
      
      - name: install
        uses: actions/setup-python@main
        with:
          python-version: 3.x
          architecture: x64

      - name: Install
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Fetch
        run: python main.py

      - name: Commit
        run: |
          git config --local user.email "Austin__Lee@outlook.com"
          git config --local user.name "Austin Lee"
          git add .
          git commit -m "Update"

      - name: Push
        uses: EndBug/add-and-commit@v9
        with:
          author_name: Austin Lee
          author_email: Austin__Lee@outlook.com
